name: Run Postman API Tests
on:
  push:
    branches:
      - '**'
jobs: 
  api-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4		
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*  
    - name: install Newman
      run: npm install -g newman    
    - name: Run Collection
      run: newman run dataDrivenCollection.json -d UserData.json